### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Wildan-dev461** [Terpz710/Sell-PM5#1]
Add subcommand like /sell inventory (that sell all item in our inventory) and /sell all (sell the same type of item we hold), Just my suggest :)

**Comment by Terpz710** [comment]
I will later today. The plugin is still in beta. Feel free to contribut!

**Comment by Wildan-dev461** [comment]
> I will later today. The plugin is still in beta. Feel free to contribut!

Thanks!
