### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ParadoxPlays** [Terpz710/Sell-PM5#2]
Plugin Version: I just downloaded the zip file from github
Server Version: 1.20.50 (I can join on latest version)
Pocketmine-MP Version: 5.10.0
Probably isn't working because plugin is in beta but whatever.

Error:
THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: Sell

Thread: Main
Error: Call to undefined method cooldogedev\BedrockEconomy\BedrockEconomy::getAPI()
File: plugins/Sell/src/Terpz710/Sell/Economy/EconomyManager
Line: 74
Type: Error
Backtrace:
#0 plugins/Sell/src/Terpz710/Sell/Commands/SellCommand(89): Terpz710\Sell\Economy\EconomyManager->addMoney(object pocketmine\player\Player#182295, int 10, object Closure#94373)
#1 pmsrc/src/command/SimpleCommandMap(212): Terpz710\Sell\Commands\SellCommand->execute(object pocketmine\player\Player#182295, string[4] sell, array[0])
#2 pmsrc/src/Server(1425): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#182295, string[4] sell)
#3 pmsrc/src/player/Player(1512): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#182295, string[4] sell)
#4 pmsrc/src/network/mcpe/handler/InGamePacketHandler(821): pocketmine\player\Player->chat(string[5] /sell)
#5 pmsrc/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket(55): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#189160)
#6 pmsrc/src/network/mcpe/NetworkSession(448): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#95524)
#7 pmsrc/src/network/mcpe/NetworkSession(386): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#189160, string[27] M./sell..A.......\........H)
#8 pmsrc/src/network/mcpe/raklib/RakLibInterface(219): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[31] ..e./N..aX.......].1]O...;.....)
#9 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[40] .&/M..#...{.>.AZ.*m..&..........n.~..mQ.)
#10 pmsrc/src/network/mcpe/raklib/RakLibInterface(111): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#199588)
#11 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\TimeTrackingSleeperHandler->pocketmine\{closure}()
#13 pmsrc/src/TimeTrackingSleeperHandler(77): pocketmine\snooze\SleeperHandler->processNotifications()
#14 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#15 pmsrc/src/Server(1690): pocketmine\snooze\SleeperHandler->sleepUntil(float 1706587595.1762)
#16 pmsrc/src/Server(1065): pocketmine\Server->tickProcessor()
#17 pmsrc/src/PocketMine(341): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
#18 pmsrc/src/PocketMine(364): pocketmine\server()
#19 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

Code:
[65]         if ($this->eco == null) {
[66]             $this->plugin->getLogger()->warning("You don't have an Economy plugin");
[67]             return;
[68]         }
[69]         switch ($this->eco->getName()) {
[70]             case "EconomyAPI":
[71]                 $callback($this->eco->addMoney($player->getName(), $amount, EconomyAPI::RET_SUCCESS));
[72]                 break;
[73]             case "BedrockEconomy":
[74]                 $this->eco->getAPI()->addToPlayerBalance($player->getName(), (int) ceil($amount), ClosureContext::create(static function(bool $success) use($callback) : void {
[75]                     $callback($success);
[76]                 }));
[77]                 break;
[78]         }
[79]     }
[80] }

**Comment by Terpz710** [comment]
Do you have bedrock economy installed? Also this bug is on BedrockEconomy end but I’ll look into it.

**Comment by ParadoxPlays** [comment]
Yes, I have the latest version of bedrockeconomy (should be latest)
installed

**Comment by Terpz710** [comment]
Yea it’s a BedrockEconomy related issue. Mostly all plugins that uses that plugin is affected. I sent an issue myself so we’ll see.

**Comment by Terpz710** [comment]
I fixed the issue. Please download the latest version through poggit.

**Comment by Terpz710** [comment]
Thank you for bringing this to my concern.
