### ISSUE TITLE
Can you make a MoneyFloatintext leaderboard or ChestShop

### ISSUE THREAD

**Issue by DragonfireHD** [Terpz710/Sell-PM5#3]
Idea can you make a TopMoneyFloatingText 
Or ChestShop

**Comment by Terpz710** [comment]
What? Also wrong plugin buddy this is sell not a Ecomony plugin unless you’re talking about the top players that sold the most items and show their sales.

**Comment by DragonfireHD** [comment]
This is a idea for the next Plugin this is is a Idea for you not a error think

**Comment by Terpz710** [comment]
An idea for me? Yea no I’m good if you pay me to do it than maybe but I don’t have any intentions on making any plugins like that.
